// Define available languages
export type Language = 'pt-BR' | 'en-US';

// Translation dictionaries
export const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Navigation
    'nav.how_it_works': 'Como Funciona',
    'nav.pricing': 'Preços',
    'nav.faq': 'FAQ',
    'nav.free_trial': 'Teste Grátis',
    
    // Hero section
    'hero.title': 'Cardápios semanais personalizados para sua família',
    'hero.subtitle': 'Receba no WhatsApp cardápios personalizados, lista de compras e receitas. Economize tempo e dinheiro, sem estresse.',
    'hero.cta': 'Comece Grátis',
    'hero.secondary_cta': 'Saiba Mais',
    'hero.cta.trial': 'Comece seu teste de 7 dias grátis',
    'hero.cta.no_commitment': '✨ Sem compromisso • Cancele quando quiser',
    'hero.whatsapp.badge': 'Receba no WhatsApp',
    
    // Hero carousel slides
    'hero.slide1.title': 'Planejamento de',
    'hero.slide1.subtitle': 'Refeições para Mães',
    'hero.slide1.tagline': 'Introdução alimentar e receitas práticas',
    'hero.slide1.description': 'Receba cardápios especiais para bebês iniciando sólidos e receitas práticas para toda a família, sem complicação.',
    'hero.slide1.alt': 'Mãe preparando refeição saudável para bebê',
    'hero.slide1.feature1': 'Introdução alimentar',
    'hero.slide1.feature2': 'Para toda família',
    'hero.slide1.feature3': 'Receitas rápidas',
    'hero.slide1.feature4': 'Lista organizada',
    
    'hero.slide2.title': 'Planejamento de',
    'hero.slide2.subtitle': 'Refeições Especiais',
    'hero.slide2.tagline': 'Respeitando suas restrições alimentares',
    'hero.slide2.description': 'Cardápios personalizados para vegetarianos, intolerantes à lactose, celíacos e outras necessidades específicas.',
    'hero.slide2.alt': 'Pessoa preparando refeição com alimentos para dietas especiais',
    'hero.slide2.feature1': 'Sem restrições',
    'hero.slide2.feature2': 'Nutrição balanceada',
    'hero.slide2.feature3': 'Entrega semanal',
    'hero.slide2.feature4': 'Ingredientes certos',
    
    'hero.slide3.title': 'Planejamento de',
    'hero.slide3.subtitle': 'Refeições Práticas',
    'hero.slide3.tagline': 'Para profissionais ocupados',
    'hero.slide3.description': 'Cardápios otimizados para quem tem pouco tempo, mas não abre mão de uma alimentação saudável e saborosa.',
    'hero.slide3.alt': 'Profissional ocupado preparando refeição rápida e saudável',
    'hero.slide3.feature1': 'Vida corrida',
    'hero.slide3.feature2': 'Casais e solteiros',
    'hero.slide3.feature3': 'Preparo rápido',
    'hero.slide3.feature4': 'Compra eficiente',
    
    // Features section
    'features.title': 'Cardápios que se adaptam à sua família',
    'features.subtitle': 'Soluções práticas para o dia a dia',
    'features.personalized.title': 'Personalizado',
    'features.personalized.description': 'Cardápios adaptados às preferências e restrições alimentares da sua família.',
    'features.practical.title': 'Prático',
    'features.practical.description': 'Receba tudo pelo WhatsApp, sem precisar baixar aplicativos ou fazer login.',
    'features.economical.title': 'Econômico',
    'features.economical.description': 'Economize tempo e dinheiro com listas de compras otimizadas e receitas aproveitáveis.',
    'features.nutritious.title': 'Nutritivo',
    'features.nutritious.description': 'Cardápios elaborados por nutricionistas, garantindo refeições balanceadas.',
    'features.adaptable.title': 'Adaptável',
    'features.adaptable.description': 'Receitas que se adaptam à rotina da sua família, com opções rápidas para dias corridos.',
    'features.supportive.title': 'Suporte',
    'features.supportive.description': 'Atendimento personalizado para ajustar seu cardápio quando necessário.',
    
    // Features component
    'features.component.heading': 'Tudo que você precisa',
    'features.component.subheading': 'Simplificamos o planejamento das refeições para mães ocupadas, pessoas com restrições alimentares e profissionais com rotina corrida.',
    'features.component.card1.title': 'Cardápio Personalizado',
    'features.component.card1.description': 'Refeições planejadas com base no perfil da sua família, idade das crianças e preferências alimentares.',
    'features.component.card2.title': 'Lista de Compras Organizada',
    'features.component.card2.description': 'Ingredientes organizados por categoria com checkboxes para uma compra mais eficiente.',
    'features.component.card3.title': 'Culinária Brasileira',
    'features.component.card3.description': 'Pratos que fazem parte da nossa cultura, com ingredientes sazonais e de fácil acesso.',
    'features.component.card4.title': 'Nutrição Balanceada',
    'features.component.card4.description': 'Refeições equilibradas para famílias, pessoas com restrições alimentares e profissionais ocupados.',
    'features.component.card5.title': 'Praticidade Total',
    'features.component.card5.description': 'Sem aplicativo, sem login, sem complicação. Tudo direto no seu WhatsApp.',
    'features.component.card6.title': 'Para Todos os Perfis',
    'features.component.card6.description': 'Famílias com bebês, pessoas com restrições alimentares e profissionais com pouco tempo para cozinhar.',
    
    // Blog section
    'blog.title': 'Blog e Receitas',
    'blog.subtitle': 'Dicas, cardápios e receitas para inspirar sua rotina alimentar',
    'blog.servings': 'porções',
    'blog.readMore': 'Ler mais',
    'blog.viewMore': 'Ver mais artigos',
    
    // How it works section
    'how.title': 'Como Funciona',
    'how.subtitle': 'Três passos simples para transformar sua rotina alimentar',
    'how.step1.title': 'Cadastre-se',
    'how.step1.description': 'Preencha um breve questionário sobre sua família, preferências e restrições alimentares.',
    'how.step2.title': 'Receba seu cardápio',
    'how.step2.description': 'Toda semana você receberá no WhatsApp um cardápio personalizado com lista de compras.',
    'how.step3.title': 'Prepare as refeições',
    'how.step3.description': 'Siga as receitas simples e práticas para preparar refeições deliciosas para sua família.',
    
    // HowItWorks component
    'how.component.heading': 'Como funciona?',
    'how.component.subheading': 'Em apenas 3 passos simples, você terá um planejamento completo de refeições para toda a semana.',
    'how.component.step1.title': 'Crie seu perfil',
    'how.component.step1.description': 'Conte sobre sua família, idades das crianças, restrições alimentares e preferências.',
    'how.component.step2.title': 'Receba no WhatsApp',
    'how.component.step2.description': 'Toda segunda-feira receba seu cardápio da semana e lista de compras organizada.',
    'how.component.step3.title': 'Cozinhe e aproveite',
    'how.component.step3.description': 'Siga o planejamento e tenha mais tempo para curtir momentos em família.',
    
    // Pricing section
    'pricing.title': 'Planos e Preços',
    'pricing.subtitle': 'Escolha o plano ideal para sua família',
    'pricing.monthly.title': 'Mensal',
    'pricing.monthly.price': 'R$29,90',
    'pricing.monthly.period': '/mês',
    'pricing.monthly.description': 'Ideal para experimentar o serviço',
    'pricing.quarterly.title': 'Trimestral',
    'pricing.quarterly.price': 'R$79,90',
    'pricing.quarterly.period': '/trimestre',
    'pricing.quarterly.description': 'Economize R$9,80 por trimestre',
    'pricing.annual.title': 'Anual',
    'pricing.annual.price': 'R$299,90',
    'pricing.annual.period': '/ano',
    'pricing.annual.description': 'Economize R$58,90 por ano',
    'pricing.feature.cardapios': 'Cardápios semanais personalizados',
    'pricing.feature.lista': 'Lista de compras organizada',
    'pricing.feature.receitas': 'Receitas detalhadas',
    'pricing.feature.ajustes': 'Ajustes sob demanda',
    'pricing.feature.suporte': 'Suporte via WhatsApp',
    'pricing.cta': 'Começar Agora',
    'pricing.trial': 'Teste grátis de 7 dias',
    
    // Pricing component
    'pricing.component.heading': 'Planos que cabem no seu orçamento',
    'pricing.component.subheading': 'Comece gratuitamente e descubra como é fácil planejar as refeições da família.',
    'pricing.component.badge': 'Teste Grátis',
    'pricing.component.plan.title': 'Plano Mensal',
    'pricing.component.plan.price': 'R$ 14,90',
    'pricing.component.plan.period': '/mês',
    'pricing.component.plan.trial': '7 dias grátis para testar',
    'pricing.component.features.1': 'Cardápio semanal personalizado',
    'pricing.component.features.2': 'Lista de compras organizada',
    'pricing.component.features.3': 'Refeições para almoço e jantar',
    'pricing.component.features.4': 'Ingredientes sazonais e locais',
    'pricing.component.features.5': 'Suporte via WhatsApp',
    'pricing.component.features.6': 'Receitas da culinária brasileira',
    'pricing.component.features.7': 'Cancelamento a qualquer momento',
    'pricing.component.cta': 'Comece seu teste grátis agora',
    'pricing.component.disclaimer': 'Sem compromisso • Sem fidelidade • Cancele quando quiser',
    'pricing.component.customization': '💡 <strong>Personalizações extras:</strong> Planos especiais disponíveis para famílias com necessidades específicas (vegano, sem glúten, diabético, etc.)',
    
    // Testimonials component
    'testimonials.component.heading': 'O que nossos usuários estão falando',
    'testimonials.component.subheading': 'Famílias, pessoas com restrições alimentares e profissionais ocupados já transformaram sua rotina.',
    'testimonials.component.rating.text': 'Baseado em 127 avaliações',
    'testimonials.component.testimonial1.name': 'Maria Silva',
    'testimonials.component.testimonial1.role': 'Mãe de 2 filhos',
    'testimonials.component.testimonial1.content': 'Minha vida mudou! Não preciso mais ficar estressada pensando no que fazer para o almoço. As receitas são deliciosas e os ingredientes sempre frescos.',
    'testimonials.component.testimonial1.avatar': '👩‍🍳',
    'testimonials.component.testimonial2.name': 'Ana Costa',
    'testimonials.component.testimonial2.role': 'Mãe de bebê de 8 meses',
    'testimonials.component.testimonial2.content': 'Perfeito para quem está introduzindo alimentação sólida. As sugestões são nutritivas e adequadas para a idade do meu filho.',
    'testimonials.component.testimonial2.avatar': '👶',
    'testimonials.component.testimonial3.name': 'Carlos Mendes',
    'testimonials.component.testimonial3.role': 'Executivo, intolerante à lactose',
    'testimonials.component.testimonial3.content': 'Finalmente encontrei um serviço que entende minhas restrições alimentares. Recebo receitas deliciosas sem lactose toda semana.',
    'testimonials.component.testimonial3.avatar': '👨‍💼',
    'testimonials.component.testimonial4.name': 'Rafael & Juliana',
    'testimonials.component.testimonial4.role': 'Casal profissional',
    'testimonials.component.testimonial4.content': 'Economizamos tempo e dinheiro. A lista de compras é super organizada e não desperdiçamos mais comida. Perfeito para nossa rotina corrida!',
    'testimonials.component.testimonial4.avatar': '👫',
    
    // FAQ section
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Tire suas dúvidas sobre o Cardápio Fácil e como podemos ajudar sua família',
    'faq.item1.question': 'Como funciona o Cardápio Fácil?',
    'faq.item1.answer': 'Após se cadastrar, você receberá semanalmente no seu WhatsApp um cardápio personalizado com base no perfil da sua família, incluindo lista de compras organizada e receitas detalhadas. Tudo isso sem precisar baixar aplicativos ou fazer login em plataformas complicadas.',
    'faq.item2.question': 'Quanto custa o serviço?',
    'faq.item2.answer': 'Oferecemos um teste gratuito de 7 dias para que você experimente o serviço sem compromisso. Após esse período, o valor é de R$29,90 por mês, com possibilidade de cancelamento a qualquer momento.',
    'faq.item3.question': 'Como são elaborados os cardápios?',
    'faq.item3.answer': 'Nossos cardápios são elaborados por nutricionistas especializados, considerando as necessidades nutricionais da sua família, preferências alimentares e eventuais restrições. Utilizamos ingredientes sazonais e de fácil acesso em supermercados.',
    'faq.item4.question': 'Posso personalizar meu cardápio?',
    'faq.item4.answer': 'Sim! Durante o cadastro, você informa o perfil da sua família, incluindo número de pessoas, idades, preferências e restrições alimentares. Além disso, você pode solicitar ajustes a qualquer momento respondendo às mensagens no WhatsApp.',
    'faq.item5.question': 'Como funciona para famílias com bebês?',
    'faq.item5.answer': 'Para famílias com bebês, incluímos orientações específicas para introdução alimentar, respeitando a idade da criança e as recomendações pediátricas atuais, com receitas adaptadas que toda a família pode consumir.',
    'faq.item6.question': 'E se eu tiver restrições alimentares?',
    'faq.item6.answer': 'Nossos cardápios são totalmente adaptáveis para diversas restrições alimentares, como intolerância à lactose, glúten, vegetarianismo, veganismo e alergias específicas. Basta informar suas necessidades no cadastro.',
    'faq.item7.question': 'Posso cancelar a qualquer momento?',
    'faq.item7.answer': 'Sim, você pode cancelar sua assinatura a qualquer momento, sem multas ou taxas adicionais. Basta enviar uma mensagem pelo WhatsApp solicitando o cancelamento.',
    'faq.item8.question': 'Como é feito o pagamento?',
    'faq.item8.answer': 'O pagamento é feito mensalmente via PIX ou cartão de crédito. Você receberá as instruções de pagamento após o período de teste gratuito.',
    
    // CTA section
    'cta.title': 'Pronto para simplificar sua rotina alimentar?',
    'cta.subtitle': 'Comece seu teste grátis de 7 dias agora e receba cardápios personalizados para sua família',
    'cta.form.name.label': 'Nome completo',
    'cta.form.name.placeholder': 'Digite seu nome completo',
    'cta.form.name.error': 'Nome deve ter pelo menos 3 caracteres',
    'cta.form.whatsapp.label': 'WhatsApp',
    'cta.form.whatsapp.placeholder': '(00) 00000-0000',
    'cta.form.whatsapp.error': 'WhatsApp inválido',
    'cta.form.familySize.label': 'Tamanho da família',
    'cta.form.familySize.placeholder': 'Quantas pessoas?',
    'cta.form.familySize.error': 'Selecione o tamanho da família',
    'cta.form.familySize.option.1': '1 pessoa',
    'cta.form.familySize.option.2': '2 pessoas',
    'cta.form.familySize.option.3': '3 pessoas',
    'cta.form.familySize.option.4': '4 pessoas',
    'cta.form.familySize.option.5': '5 ou mais pessoas',
    'cta.form.dietaryRestrictions.label': 'Restrições alimentares',
    'cta.form.dietaryRestrictions.placeholder': 'Alguma restrição ou preferência?',
    'cta.form.dietaryRestrictions.option.none': 'Nenhuma restrição',
    'cta.form.dietaryRestrictions.option.vegetarian': 'Vegetariano',
    'cta.form.dietaryRestrictions.option.lactose': 'Sem lactose',
    'cta.form.dietaryRestrictions.option.gluten': 'Sem glúten',
    'cta.form.dietaryRestrictions.option.diabetic': 'Diabético',
    'cta.form.dietaryRestrictions.option.multiple': 'Múltiplas restrições',
    'cta.form.button.loading': 'Processando...',
    'cta.form.button.submit': 'Começar teste grátis de 7 dias',
    'cta.form.terms.text': 'Aceito os',
    'cta.form.terms.link': 'termos de uso',
    'cta.form.terms.error': 'Você precisa aceitar os termos de uso',
    'cta.form.privacy.text': 'Aceito a',
    'cta.form.privacy.link': 'política de privacidade',
    'cta.form.privacy.error': 'Você precisa aceitar a política de privacidade',
    'cta.form.confirmation': 'Seu primeiro cardápio chegará em até 24 horas após a confirmação do cadastro.',
    'cta.form.error.title': 'Por favor, corrija os erros no formulário',
    'cta.form.error.description': 'Alguns campos precisam ser preenchidos corretamente.',
    'cta.form.success.title': 'Cadastro realizado com sucesso!',
    'cta.form.success.description': 'Enviamos uma mensagem de boas-vindas para o seu WhatsApp. Verifique seu celular.',
    'cta.button': 'Começar Teste Grátis',
    'cta.freeTrial': '7 dias grátis • Sem compromisso',
    'cta.form.title': 'Cadastre-se gratuitamente',
    'cta.form.description': 'Leva menos de 2 minutos para começar',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados',
    'footer.terms': 'Termos de Uso',
    'footer.privacy': 'Política de Privacidade',
    'footer.contact': 'Contato',
    'footer.brand.description': 'Planejamento de refeições personalizadas para famílias brasileiras, direto no seu WhatsApp.',
    'footer.product': 'Produto',
    'footer.how_it_works': 'Como funciona',
    'footer.pricing': 'Preços',
    'footer.free_trial': 'Teste grátis',
    'footer.faq': 'Perguntas frequentes',
    'footer.support': 'Suporte',
    'footer.help_center': 'Central de ajuda',
    'footer.whatsapp': 'WhatsApp',
    'footer.feedback': 'Feedback',
    'footer.legal': 'Legal',
    'footer.cookies': 'Cookies',
    'footer.lgpd': 'LGPD',
    'footer.copyright': '© 2025 CardapioFacil. Feito com',
    'footer.copyright.for': 'para famílias brasileiras.',
    'footer.company': 'Empresa responsável:',
    'footer.cnpj': 'CNPJ:',
    'footer.solution': 'Uma solução desenvolvida pela CraftCode',
    
    // Theme toggle
    'theme.toggle': 'Alternar tema',
    
    // Language toggle
    'language.toggle': 'Mudar idioma',
    'language.pt': 'Português',
    'language.en': 'English',
    
    // SEO metadata
    'seo.home.title': 'Mamma\'s Plate Plan - Planejamento de refeições saudáveis',
    'seo.home.description': 'Planejamento de refeições saudáveis e deliciosas para toda a família. Economize tempo e dinheiro com nosso serviço de cardápio fácil.',
    'seo.home.keywords': 'planejamento de refeições, cardápio semanal, receitas saudáveis, economia de tempo, economia de dinheiro',
    'seo.thankyou.title': 'Obrigado por se inscrever - Mamma\'s Plate Plan',
    'seo.thankyou.description': 'Agradecemos por se inscrever no Mamma\'s Plate Plan. Você receberá seu primeiro cardápio personalizado em breve.',
    'seo.terms.title': 'Termos de Uso - Mamma\'s Plate Plan',
    'seo.terms.description': 'Termos e condições de uso do serviço Mamma\'s Plate Plan. Leia atentamente antes de utilizar nosso serviço.',
    'seo.privacy.title': 'Política de Privacidade - Mamma\'s Plate Plan',
    'seo.privacy.description': 'Nossa política de privacidade explica como coletamos, usamos e protegemos suas informações pessoais no Mamma\'s Plate Plan.',
    'seo.notfound.title': 'Página não encontrada - Mamma\'s Plate Plan',
    'seo.notfound.description': 'A página que você está procurando não foi encontrada. Volte para a página inicial do Mamma\'s Plate Plan.',
    'notfound.error': '404',
    'notfound.message': 'Oops! Página não encontrada',
    'notfound.return': 'Voltar para a Página Inicial',
    
    // ThankYou page
    'thankyou.title': 'Obrigado pelo seu cadastro!',
    'thankyou.subtitle': 'Estamos preparando seu cardápio personalizado.',
    'thankyou.profile.title': 'Resumo do seu perfil:',
    'thankyou.profile.name': 'Nome:',
    'thankyou.profile.family': 'Composição familiar:',
    'thankyou.profile.restrictions': 'Restrições alimentares:',
    'thankyou.profile.notInformed': 'Não informado',
    'thankyou.family.single': 'Apenas eu',
    'thankyou.family.couple': 'Casal sem filhos',
    'thankyou.family.baby': 'Casal com bebê (até 2 anos)',
    'thankyou.family.children': 'Família com crianças (2-12 anos)',
    'thankyou.family.teens': 'Família com adolescentes',
    'thankyou.family.mixed': 'Família mista (várias idades)',
    'thankyou.diet.none': 'Nenhuma restrição',
    'thankyou.diet.vegetarian': 'Vegetariano',
    'thankyou.diet.lactose': 'Sem lactose',
    'thankyou.diet.gluten': 'Sem glúten',
    'thankyou.diet.diabetic': 'Diabético',
    'thankyou.diet.multiple': 'Múltiplas restrições',
    'thankyou.whatsapp.title': 'Aguarde mensagem no WhatsApp',
    'thankyou.whatsapp.message': 'Enviaremos uma mensagem para {whatsapp} em até 24 horas com seu primeiro cardápio semanal.',
    'thankyou.whatsapp.defaultNumber': 'seu número',
    'thankyou.trial.title': 'Seu teste gratuito começou',
    'thankyou.trial.message': 'Você tem acesso a 7 dias de cardápios personalizados. Não se preocupe, avisaremos antes do término.',
    'thankyou.button.home': 'Voltar para a página inicial',
    
    // TermsOfUse page
    'terms.title': 'Termos de Uso',
    'terms.lastUpdated': 'Última atualização:',
    
    // PrivacyPolicy page
    'privacy.title': 'Política de Privacidade',
    'privacy.lastUpdated': 'Última atualização:',
    'privacy.section1.title': '1. Introdução',
    'privacy.section1.content1': 'O Cardápio Fácil está comprometido em proteger sua privacidade. Esta Política de Privacidade explica como coletamos, usamos, divulgamos e protegemos suas informações pessoais quando você utiliza nosso serviço de planejamento de refeições via WhatsApp.',
    'privacy.section1.content2': 'Ao utilizar nosso serviço, você concorda com a coleta e uso de informações de acordo com esta política. Esta política está em conformidade com a Lei Geral de Proteção de Dados (LGPD) do Brasil.',
    'privacy.section2.title': '2. Informações que Coletamos',
    'privacy.section2.content': 'Para fornecer e melhorar nosso serviço, coletamos diversos tipos de informações, incluindo:',
    'privacy.section2.1.title': '2.1 Informações Pessoais',
    'privacy.section2.1.content': 'Quando você se registra e utiliza o Cardápio Fácil, podemos coletar as seguintes informações pessoais:',
    'privacy.section2.1.item1': 'Nome completo',
    'privacy.section2.1.item2': 'Número de telefone',
    'privacy.section2.1.item3': 'Endereço de e-mail',
    'privacy.section2.1.item4': 'Informações de pagamento (processadas por provedores de pagamento terceirizados)',
    'privacy.section2.1.item5': 'Preferências alimentares e restrições dietéticas',
    'privacy.section2.1.item6': 'Composição familiar (número de pessoas, idades)',
    'privacy.section2.2.title': '2.2 Dados de Uso',
    'privacy.section2.2.content': 'Também coletamos informações sobre como você acessa e usa nosso serviço, incluindo:',
    'privacy.section2.2.item1': 'Interações com nosso serviço via WhatsApp',
    'privacy.section2.2.item2': 'Preferências de cardápio e avaliações de receitas',
    'privacy.section2.2.item3': 'Frequência de uso do serviço',
    'privacy.section2.2.item4': 'Padrões de uso e comportamento',
    'privacy.section3.title': '3. Como Usamos Suas Informações',
    'privacy.section3.content': 'Utilizamos as informações coletadas para:',
    'privacy.section3.item1': 'Fornecer e manter nosso serviço de planejamento de refeições',
    'privacy.section3.item2': 'Personalizar cardápios de acordo com suas preferências e necessidades',
    'privacy.section3.item3': 'Processar pagamentos e gerenciar sua assinatura',
    'privacy.section3.item4': 'Enviar notificações relacionadas ao serviço via WhatsApp',
    'privacy.section3.item5': 'Melhorar nosso serviço com base no feedback e padrões de uso',
    'privacy.section3.item6': 'Fornecer suporte ao cliente',
    'privacy.section3.item7': 'Cumprir obrigações legais',
    'privacy.keywords': 'política de privacidade, lgpd, proteção de dados, cardápio fácil, termos de uso',
    'privacy.section4.title': '4. Compartilhamento de Informações',
    'privacy.section4.content': 'Podemos compartilhar suas informações pessoais com:',
    'privacy.section4.item1': 'Provedores de serviços terceirizados que nos auxiliam na operação de nosso serviço (como processadores de pagamento e serviços de hospedagem)',
    'privacy.section4.item2': 'Autoridades legais quando exigido por lei ou para proteger nossos direitos',
    'privacy.section4.item3': 'Parceiros de negócios com seu consentimento explícito',
    'privacy.section4.content2': 'Não vendemos, alugamos ou comercializamos suas informações pessoais para terceiros.',
    'privacy.section5.title': '5. Segurança de Dados',
    'privacy.section5.content': 'Implementamos medidas de segurança técnicas e organizacionais apropriadas para proteger suas informações pessoais contra acesso não autorizado, alteração, divulgação ou destruição acidental ou ilegal.',
    'privacy.section5.content2': 'No entanto, nenhum método de transmissão pela Internet ou método de armazenamento eletrônico é 100% seguro. Embora nos esforcemos para usar meios comercialmente aceitáveis para proteger suas informações pessoais, não podemos garantir sua segurança absoluta.',
    'privacy.section6.title': '6. Cookies e Tecnologias Semelhantes',
    'privacy.section6.content': 'Nosso site e serviços podem usar "cookies" e outras tecnologias de rastreamento para coletar informações sobre sua atividade, navegador e dispositivo. Você pode instruir seu navegador a recusar todos os cookies ou a indicar quando um cookie está sendo enviado. No entanto, se você não aceitar cookies, algumas partes do nosso serviço podem não funcionar corretamente.',
    'privacy.section7.title': '7. Período de Retenção',
    'privacy.section7.content': 'Mantemos suas informações pessoais apenas pelo tempo necessário para os fins estabelecidos nesta Política de Privacidade, a menos que um período de retenção mais longo seja exigido ou permitido por lei.',
    'privacy.section7.content2': 'Quando não tivermos mais necessidade legítima de processar suas informações pessoais, as excluiremos ou anonimizaremos. Se isso não for possível, armazenaremos suas informações pessoais de forma segura e as isolaremos de qualquer processamento adicional até que a exclusão seja possível.',
    'privacy.section8.title': '8. Seus Direitos',
    'privacy.section8.content': 'De acordo com a LGPD e outras leis de proteção de dados aplicáveis, você tem os seguintes direitos:',
    'privacy.section8.item1': 'Acesso: Direito de acessar suas informações pessoais que mantemos.',
    'privacy.section8.item2': 'Correção: Direito de corrigir informações imprecisas ou incompletas.',
    'privacy.section8.item3': 'Exclusão: Direito de solicitar a exclusão de suas informações pessoais.',
    'privacy.section8.item4': 'Restrição: Direito de solicitar a restrição do processamento de suas informações.',
    'privacy.section8.item5': 'Portabilidade: Direito de receber suas informações em um formato estruturado e transferível.',
    'privacy.section8.item6': 'Objeção: Direito de se opor ao processamento de suas informações.',
    'privacy.section8.item7': 'Retirada de Consentimento: Direito de retirar seu consentimento a qualquer momento.',
    'privacy.section8.content2': 'Para exercer qualquer um desses direitos, entre em contato conosco através dos canais indicados na seção "Contato" abaixo.',
    'privacy.section9.title': '9. Transferências Internacionais de Dados',
    'privacy.section9.content1': 'Suas informações podem ser transferidas e mantidas em computadores localizados fora de seu estado, província, país ou outra jurisdição governamental, onde as leis de proteção de dados podem ser diferentes.',
    'privacy.section9.content2': 'Quando transferimos seus dados para fora do Brasil, garantimos que medidas adequadas de proteção sejam implementadas, como cláusulas contratuais padrão ou certificações de proteção de dados reconhecidas.',
    'privacy.section10.title': '10. Crianças',
    'privacy.section10.content': 'Nosso serviço não se destina a pessoas menores de 18 anos. Não coletamos intencionalmente informações pessoais de crianças. Se você é pai ou responsável e acredita que seu filho nos forneceu informações pessoais, entre em contato conosco para que possamos tomar as medidas necessárias.',
    'privacy.section11.title': '11. Alterações a Esta Política',
    'privacy.section11.content1': 'Podemos atualizar nossa Política de Privacidade periodicamente. Notificaremos você sobre quaisquer alterações publicando a nova Política de Privacidade nesta página e, se as alterações forem significativas, enviaremos uma notificação via WhatsApp ou e-mail.',
    'privacy.section11.content2': 'Recomendamos que você revise esta Política de Privacidade periodicamente para quaisquer alterações.',
    'privacy.section12.title': '12. Contato',
    'privacy.section12.content': 'Se você tiver dúvidas ou preocupações sobre esta Política de Privacidade ou nossas práticas de dados, entre em contato conosco:',
    'privacy.section12.email': 'E-mail:',
    'privacy.section12.emailAddress': 'privacidade@cardapiofacil.online',
    'privacy.section12.address': 'Endereço:',
    'privacy.section12.addressValue': 'Av. Paulista, 171, São Paulo - SP, 01310-100',
    'privacy.section12.dpo': 'Encarregado de Proteção de Dados (DPO):',
    'privacy.section12.dpoEmail': 'dpo@cardapiofacil.online',
    'terms.section1.title': '1. Aceitação dos Termos',
    'terms.section1.content': 'Ao acessar e utilizar o serviço Cardápio Fácil, você concorda em cumprir e estar vinculado aos seguintes termos e condições. Se você não concordar com qualquer parte destes termos, não poderá acessar ou utilizar nossos serviços.',
    'terms.section2.title': '2. Descrição do Serviço',
    'terms.section2.content': 'O Cardápio Fácil é um serviço de planejamento de refeições personalizadas entregue via WhatsApp. Nosso serviço oferece cardápios semanais, receitas, listas de compras e dicas nutricionais adaptadas às necessidades e preferências de cada família.',
    'terms.section3.title': '3. Elegibilidade',
    'terms.section3.content': 'Para utilizar o Cardápio Fácil, você deve ter pelo menos 18 anos de idade e possuir capacidade legal para celebrar contratos vinculativos. Ao utilizar nosso serviço, você declara e garante que atende a esses requisitos.',
    'terms.section4.title': '4. Cadastro e Conta',
    'terms.section4.content': 'Para acessar determinados recursos do nosso serviço, você precisará criar uma conta. Você é responsável por manter a confidencialidade das informações da sua conta e por todas as atividades que ocorrerem nela. Você concorda em:',
    'terms.section4.item1': 'Fornecer informações precisas, atuais e completas durante o processo de registro;',
    'terms.section4.item2': 'Manter e atualizar prontamente suas informações de registro;',
    'terms.section4.item3': 'Notificar-nos imediatamente sobre qualquer uso não autorizado da sua conta ou qualquer outra violação de segurança.',
    'terms.section5.title': '5. Planos e Pagamentos',
    'terms.section5.content': 'O Cardápio Fácil oferece diferentes planos de assinatura. Ao se inscrever em um plano pago, você concorda em pagar todas as taxas aplicáveis conforme especificado no momento da compra. Os pagamentos são processados por provedores de pagamento terceirizados e estão sujeitos aos termos e condições desses provedores.',
    'terms.section5.content2': 'Você pode cancelar sua assinatura a qualquer momento, mas não haverá reembolsos para períodos parciais de assinatura. Reservamo-nos o direito de alterar os preços de nossos serviços a qualquer momento, com aviso prévio adequado.',
    'terms.section6.title': '6. Uso Aceitável',
    'terms.section6.content': 'Você concorda em usar o Cardápio Fácil apenas para fins legais e de acordo com estes Termos. Você não deve:',
    'terms.section6.item1': 'Usar o serviço de qualquer maneira que possa danificar, desabilitar ou sobrecarregar o serviço;',
    'terms.section6.item2': 'Tentar acessar áreas do serviço às quais você não tem permissão;',
    'terms.section6.item3': 'Usar o serviço para distribuir material publicitário ou promocional não solicitado;',
    'terms.section6.item4': 'Reproduzir, duplicar, copiar, vender, revender ou explorar qualquer parte do serviço sem autorização expressa por escrito.',
    'terms.section7.title': '7. Conteúdo e Propriedade Intelectual',
    'terms.section7.content1': 'Todo o conteúdo disponibilizado através do Cardápio Fácil, incluindo textos, gráficos, logotipos, ícones, imagens, receitas, cardápios e software, é propriedade do Cardápio Fácil ou de seus fornecedores de conteúdo e está protegido por leis de direitos autorais.',
    'terms.section7.content2': 'Você pode usar o conteúdo apenas para seu uso pessoal e não comercial. Qualquer outro uso, incluindo reprodução, modificação, distribuição, transmissão ou republicação, sem o consentimento prévio por escrito do Cardápio Fácil, é estritamente proibido.',
    'terms.section8.title': '8. Isenção de Responsabilidade',
    'terms.section8.content': 'As informações nutricionais e receitas fornecidas pelo Cardápio Fácil são apenas para fins informativos e não substituem aconselhamento médico profissional, diagnóstico ou tratamento. Sempre consulte um profissional de saúde qualificado antes de fazer alterações significativas em sua dieta, especialmente se você tiver condições médicas preexistentes.',
    'terms.section9.title': '9. Limitação de Responsabilidade',
    'terms.section9.content': 'Em nenhuma circunstância o Cardápio Fácil, seus diretores, funcionários, parceiros ou agentes serão responsáveis por quaisquer danos indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso ou incapacidade de usar o serviço.',
    'terms.section10.title': '10. Modificações do Serviço e dos Termos',
    'terms.section10.content': 'Reservamo-nos o direito de modificar ou descontinuar, temporária ou permanentemente, o serviço (ou qualquer parte dele) a qualquer momento, com ou sem aviso prévio. Também podemos revisar estes Termos de Uso a qualquer momento, a nosso critério. Ao continuar a usar o serviço após tais alterações, você concorda em estar vinculado aos termos revisados.',
    'terms.section11.title': '11. Lei Aplicável',
    'terms.section11.content': 'Estes Termos serão regidos e interpretados de acordo com as leis do Brasil, sem considerar suas disposições de conflito de leis.',
    'terms.section12.title': '12. Contato',
    'terms.section12.content': 'Se você tiver alguma dúvida sobre estes Termos, entre em contato conosco pelo e-mail: contato@cardapiofacil.online',
    'terms.keywords': 'termos de uso, condições de serviço, contrato, cardápio fácil, termos legais'
  },
  'en-US': {
    // Navigation
    'nav.how_it_works': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.free_trial': 'Free Trial',
    
    // Hero section
    'hero.title': 'Personalized weekly meal plans for your family',
    'hero.subtitle': 'Receive personalized meal plans, shopping lists, and recipes via WhatsApp. Save time and money, without stress.',
    'hero.cta': 'Start Free',
    'hero.secondary_cta': 'Learn More',
    'hero.cta.trial': 'Start your 14-day free trial',
    'hero.cta.no_commitment': '✨ No commitment • Cancel anytime',
    'hero.whatsapp.badge': 'Receive on WhatsApp',
    
    // Hero carousel slides
    'hero.slide1.title': 'Meal Planning',
    'hero.slide1.subtitle': 'For Mothers',
    'hero.slide1.tagline': 'Baby food introduction and practical recipes',
    'hero.slide1.description': 'Receive special meal plans for babies starting solids and practical recipes for the whole family, without complications.',
    'hero.slide1.alt': 'Mother preparing healthy meal for baby',
    'hero.slide1.feature1': 'Baby food introduction',
    'hero.slide1.feature2': 'For the whole family',
    'hero.slide1.feature3': 'Quick recipes',
    'hero.slide1.feature4': 'Organized shopping list',
    
    'hero.slide2.title': 'Meal Planning',
    'hero.slide2.subtitle': 'For Special Diets',
    'hero.slide2.tagline': 'Respecting your dietary restrictions',
    'hero.slide2.description': 'Customized meal plans for vegetarians, lactose intolerant, celiacs, and other specific dietary needs.',
    'hero.slide2.alt': 'Person preparing meal with special diet foods',
    'hero.slide2.feature1': 'No restrictions',
    'hero.slide2.feature2': 'Balanced nutrition',
    'hero.slide2.feature3': 'Weekly delivery',
    'hero.slide2.feature4': 'Right ingredients',
    
    'hero.slide3.title': 'Meal Planning',
    'hero.slide3.subtitle': 'For Busy Professionals',
    'hero.slide3.tagline': 'For busy professionals',
    'hero.slide3.description': 'Optimized meal plans for those with little time, but who don\'t compromise on healthy and tasty food.',
    'hero.slide3.alt': 'Busy professional preparing quick and healthy meal',
    'hero.slide3.feature1': 'Busy lifestyle',
    'hero.slide3.feature2': 'Singles and couples',
    'hero.slide3.feature3': 'Quick preparation',
    'hero.slide3.feature4': 'Efficient shopping',
    
    // Features section
    'features.title': 'Meal plans that adapt to your family',
    'features.subtitle': 'Practical solutions for everyday life',
    'features.personalized.title': 'Personalized',
    'features.personalized.description': 'Meal plans adapted to your family\'s preferences and dietary restrictions.',
    'features.practical.title': 'Practical',
    'features.practical.description': 'Receive everything via WhatsApp, no need to download apps or log in.',
    'features.economical.title': 'Economical',
    'features.economical.description': 'Save time and money with optimized shopping lists and reusable recipes.',
    'features.nutritious.title': 'Nutritious',
    'features.nutritious.description': 'Meal plans created by nutritionists, ensuring balanced meals.',
    'features.adaptable.title': 'Adaptable',
    'features.adaptable.description': 'Recipes that adapt to your family\'s routine, with quick options for busy days.',
    'features.supportive.title': 'Support',
    'features.supportive.description': 'Personalized assistance to adjust your meal plan when needed.',
    
    // Features component
    'features.component.heading': 'Everything you need',
    'features.component.subheading': 'We simplify meal planning for busy mothers, people with dietary restrictions, and professionals with hectic routines.',
    'features.component.card1.title': 'Personalized Meal Plan',
    'features.component.card1.description': 'Meals planned based on your family profile, children\'s ages, and food preferences.',
    'features.component.card2.title': 'Organized Shopping List',
    'features.component.card2.description': 'Ingredients organized by category with checkboxes for more efficient shopping.',
    'features.component.card3.title': 'Brazilian Cuisine',
    'features.component.card3.description': 'Dishes that are part of our culture, with seasonal and easily accessible ingredients.',
    'features.component.card4.title': 'Balanced Nutrition',
    'features.component.card4.description': 'Balanced meals for families, people with dietary restrictions, and busy professionals.',
    'features.component.card5.title': 'Total Convenience',
    'features.component.card5.description': 'No app, no login, no complications. Everything directly on your WhatsApp.',
    'features.component.card6.title': 'For All Profiles',
    'features.component.card6.description': 'Families with babies, people with dietary restrictions, and professionals with little time to cook.',
    
    // Blog section
    'blog.title': 'Blog & Recipes',
    'blog.subtitle': 'Tips, meal plans and recipes to inspire your meal routine',
    'blog.servings': 'servings',
    'blog.readMore': 'Read more',
    'blog.viewMore': 'View more articles',
    
    // How it works section
    'how.title': 'How It Works',
    'how.subtitle': 'Three simple steps to transform your meal routine',
    'how.step1.title': 'Sign Up',
    'how.step1.description': 'Fill out a brief questionnaire about your family, preferences, and dietary restrictions.',
    'how.step2.title': 'Receive your meal plan',
    'how.step2.description': 'Every week you\'ll receive a personalized meal plan with a shopping list via WhatsApp.',
    'how.step3.title': 'Prepare the meals',
    'how.step3.description': 'Follow the simple and practical recipes to prepare delicious meals for your family.',
    
    // HowItWorks component
    'how.component.heading': 'How does it work?',
    'how.component.subheading': 'In just 3 simple steps, you\'ll have a complete meal plan for the entire week.',
    'how.component.step1.title': 'Create your profile',
    'how.component.step1.description': 'Tell us about your family, children\'s ages, dietary restrictions, and preferences.',
    'how.component.step2.title': 'Receive on WhatsApp',
    'how.component.step2.description': 'Every Monday receive your weekly meal plan and organized shopping list.',
    'how.component.step3.title': 'Cook and enjoy',
    'how.component.step3.description': 'Follow the plan and have more time to enjoy moments with your family.',
    
    // Pricing section
    'pricing.title': 'Plans and Pricing',
    'pricing.subtitle': 'Choose the ideal plan for your family',
    'pricing.monthly.title': 'Monthly',
    'pricing.monthly.price': '$5.99',
    'pricing.monthly.period': '/month',
    'pricing.monthly.description': 'Ideal for trying out the service',
    'pricing.quarterly.title': 'Quarterly',
    'pricing.quarterly.price': '$14.99',
    'pricing.quarterly.period': '/quarter',
    'pricing.quarterly.description': 'Save $3 per quarter',
    'pricing.annual.title': 'Annual',
    'pricing.annual.price': '$59.99',
    'pricing.annual.period': '/year',
    'pricing.annual.description': 'Save $12 per year',
    'pricing.feature.cardapios': 'Personalized weekly meal plans',
    'pricing.feature.lista': 'Organized shopping list',
    'pricing.feature.receitas': 'Detailed recipes',
    'pricing.feature.ajustes': 'On-demand adjustments',
    'pricing.feature.suporte': 'WhatsApp support',
    'pricing.cta': 'Start Now',
    'pricing.trial': '7-day free trial',
    
    // Pricing component
    'pricing.component.heading': 'Plans that fit your budget',
    'pricing.component.subheading': 'Start for free and discover how easy it is to plan family meals.',
    'pricing.component.badge': 'Free Trial',
    'pricing.component.plan.title': 'Monthly Plan',
    'pricing.component.plan.price': '$ 4.99',
    'pricing.component.plan.period': '/month',
    'pricing.component.plan.trial': '7 days free to try',
    'pricing.component.features.1': 'Personalized weekly meal plan',
    'pricing.component.features.2': 'Organized shopping list',
    'pricing.component.features.3': 'Meals for lunch and dinner',
    'pricing.component.features.4': 'Seasonal and local ingredients',
    'pricing.component.features.5': 'WhatsApp support',
    'pricing.component.features.6': 'Brazilian cuisine recipes',
    'pricing.component.features.7': 'Cancel anytime',
    'pricing.component.cta': 'Start your free trial now',
    'pricing.component.disclaimer': 'No commitment • No loyalty period • Cancel whenever you want',
    'pricing.component.customization': '💡 <strong>Extra customizations:</strong> Special plans available for families with specific needs (vegan, gluten-free, diabetic, etc.)',
    
    // Testimonials component
    'testimonials.component.heading': 'What our users are saying',
    'testimonials.component.subheading': 'Families, people with dietary restrictions, and busy professionals have already transformed their routine.',
    'testimonials.component.rating.text': 'Based on 127 reviews',
    'testimonials.component.testimonial1.name': 'Mary Smith',
    'testimonials.component.testimonial1.role': 'Mother of 2 children',
    'testimonials.component.testimonial1.content': 'My life has changed! I no longer need to stress about what to make for lunch. The recipes are delicious and the ingredients always fresh.',
    'testimonials.component.testimonial1.avatar': '👩‍🍳',
    'testimonials.component.testimonial2.name': 'Anna Costa',
    'testimonials.component.testimonial2.role': 'Mother of an 8-month-old baby',
    'testimonials.component.testimonial2.content': 'Perfect for those introducing solid foods. The suggestions are nutritious and appropriate for my son\'s age.',
    'testimonials.component.testimonial2.avatar': '👶',
    'testimonials.component.testimonial3.name': 'Charles Miller',
    'testimonials.component.testimonial3.role': 'Executive, lactose intolerant',
    'testimonials.component.testimonial3.content': 'I finally found a service that understands my dietary restrictions. I receive delicious lactose-free recipes every week.',
    'testimonials.component.testimonial3.avatar': '👨‍💼',
    'testimonials.component.testimonial4.name': 'Robert & Julia',
    'testimonials.component.testimonial4.role': 'Professional couple',
    'testimonials.component.testimonial4.content': 'We save time and money. The shopping list is super organized and we no longer waste food. Perfect for our busy routine!',
    'testimonials.component.testimonial4.avatar': '👫',
    
    // FAQ section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Get answers to common questions about Mamma\'s Plate Plan and how we can help your family',
    'faq.item1.question': 'How does Mamma\'s Plate Plan work?',
    'faq.item1.answer': 'After signing up, you\'ll receive a personalized weekly menu on your WhatsApp based on your family\'s profile, including an organized shopping list and detailed recipes. All this without having to download apps or log into complicated platforms.',
    'faq.item2.question': 'How much does the service cost?',
    'faq.item2.answer': 'We offer a 7-day free trial so you can experience the service without commitment. After this period, the cost is $29.90 per month, with the possibility of cancellation at any time.',
    'faq.item3.question': 'How are the menus created?',
    'faq.item3.answer': 'Our menus are created by specialized nutritionists, considering your family\'s nutritional needs, food preferences, and any restrictions. We use seasonal ingredients that are easily accessible in supermarkets.',
    'faq.item4.question': 'Can I customize my menu?',
    'faq.item4.answer': 'Yes! During registration, you provide your family\'s profile, including the number of people, ages, preferences, and dietary restrictions. Additionally, you can request adjustments at any time by responding to messages on WhatsApp.',
    'faq.item5.question': 'How does it work for families with babies?',
    'faq.item5.answer': 'For families with babies, we include specific guidelines for introducing solid foods, respecting the child\'s age and current pediatric recommendations, with adapted recipes that the whole family can consume.',
    'faq.item6.question': 'What if I have dietary restrictions?',
    'faq.item6.answer': 'Our menus are fully adaptable for various dietary restrictions, such as lactose intolerance, gluten, vegetarianism, veganism, and specific allergies. Just inform us of your needs during registration.',
    'faq.item7.question': 'Can I cancel at any time?',
    'faq.item7.answer': 'Yes, you can cancel your subscription at any time, without penalties or additional fees. Simply send a message via WhatsApp requesting cancellation.',
    'faq.item8.question': 'How is payment made?',
    'faq.item8.answer': 'Payment is made monthly via PIX or credit card. You will receive payment instructions after the free trial period.',
    
    // CTA section
    'cta.title': 'Ready to simplify your meal routine?',
    'cta.subtitle': 'Start your 7-day free trial now and receive personalized menus for your family',
    'cta.form.name.label': 'Full name',
    'cta.form.name.placeholder': 'Enter your full name',
    'cta.form.name.error': 'Name must have at least 3 characters',
    'cta.form.whatsapp.label': 'WhatsApp',
    'cta.form.whatsapp.placeholder': '(00) 00000-0000',
    'cta.form.whatsapp.error': 'Invalid WhatsApp number',
    'cta.form.familySize.label': 'Family size',
    'cta.form.familySize.placeholder': 'How many people?',
    'cta.form.familySize.error': 'Please select family size',
    'cta.form.familySize.option.1': '1 person',
    'cta.form.familySize.option.2': '2 people',
    'cta.form.familySize.option.3': '3 people',
    'cta.form.familySize.option.4': '4 people',
    'cta.form.familySize.option.5': '5 or more people',
    'cta.form.dietaryRestrictions.label': 'Dietary restrictions',
    'cta.form.dietaryRestrictions.placeholder': 'Any restrictions or preferences?',
    'cta.form.dietaryRestrictions.option.none': 'No restrictions',
    'cta.form.dietaryRestrictions.option.vegetarian': 'Vegetarian',
    'cta.form.dietaryRestrictions.option.lactose': 'Lactose-free',
    'cta.form.dietaryRestrictions.option.gluten': 'Gluten-free',
    'cta.form.dietaryRestrictions.option.diabetic': 'Diabetic',
    'cta.form.dietaryRestrictions.option.multiple': 'Multiple restrictions',
    'cta.form.button.loading': 'Processing...',
    'cta.form.button.submit': 'Start 7-day free trial',
    'cta.form.terms.text': 'I accept the',
    'cta.form.terms.link': 'terms of use',
    'cta.form.terms.error': 'You must accept the terms of use',
    'cta.form.privacy.text': 'I accept the',
    'cta.form.privacy.link': 'privacy policy',
    'cta.form.privacy.error': 'You must accept the privacy policy',
    'cta.form.confirmation': 'Your first menu will arrive within 24 hours after registration confirmation.',
    'cta.form.error.title': 'Please correct the errors in the form',
    'cta.form.error.description': 'Some fields need to be filled out correctly.',
    'cta.form.success.title': 'Registration successful!',
    'cta.form.success.description': 'We sent a welcome message to your WhatsApp. Check your phone.',
    'cta.button': 'Start Free Trial',
    'cta.freeTrial': '7 days free • No commitment',
    'cta.form.title': 'Sign up for free',
    'cta.form.description': 'Takes less than 2 minutes to start',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.terms': 'Terms of Use',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact',
    'footer.brand.description': 'Personalized meal planning for Brazilian families, directly on your WhatsApp.',
    'footer.product': 'Product',
    'footer.how_it_works': 'How it works',
    'footer.pricing': 'Pricing',
    'footer.free_trial': 'Free trial',
    'footer.faq': 'Frequently asked questions',
    'footer.support': 'Support',
    'footer.help_center': 'Help center',
    'footer.whatsapp': 'WhatsApp',
    'footer.feedback': 'Feedback',
    'footer.legal': 'Legal',
    'footer.cookies': 'Cookies',
    'footer.lgpd': 'LGPD',
    'footer.copyright': '© 2025 CardapioFacil. Made with',
    'footer.copyright.for': 'for Brazilian families.',
    'footer.company': 'Responsible company:',
    'footer.cnpj': 'CNPJ:',
    'footer.solution': 'A solution developed by CraftCode',
    
    // Theme toggle
    'theme.toggle': 'Toggle theme',
    
    // Language toggle
    'language.toggle': 'Change language',
    'language.pt': 'Português',
    'language.en': 'English',
    
    // SEO metadata
    'seo.home.title': 'Mamma\'s Plate Plan - Healthy Meal Planning',
    'seo.home.description': 'Healthy and delicious meal planning for the whole family. Save time and money with our easy meal planning service.',
    'seo.home.keywords': 'meal planning, weekly menu, healthy recipes, time saving, money saving',
    'seo.thankyou.title': 'Thank You for Subscribing - Mamma\'s Plate Plan',
    'seo.thankyou.description': 'Thank you for subscribing to Mamma\'s Plate Plan. You will receive your first personalized meal plan soon.',
    'seo.terms.title': 'Terms of Use - Mamma\'s Plate Plan',
    'seo.terms.description': 'Terms and conditions for using the Mamma\'s Plate Plan service. Please read carefully before using our service.',
    'seo.privacy.title': 'Privacy Policy - Mamma\'s Plate Plan',
    'seo.privacy.description': 'Our privacy policy explains how we collect, use, and protect your personal information at Mamma\'s Plate Plan.',
    'seo.notfound.title': 'Page Not Found - Mamma\'s Plate Plan',
    'seo.notfound.description': 'The page you are looking for was not found. Return to the Mamma\'s Plate Plan homepage.',
    'notfound.error': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.return': 'Return to Home',
    
    // ThankYou page
    'thankyou.title': 'Thank you for your registration!',
    'thankyou.subtitle': 'We are preparing your personalized meal plan.',
    'thankyou.profile.title': 'Your profile summary:',
    'thankyou.profile.name': 'Name:',
    'thankyou.profile.family': 'Family composition:',
    'thankyou.profile.restrictions': 'Dietary restrictions:',
    'thankyou.profile.notInformed': 'Not provided',
    'thankyou.family.single': 'Just me',
    'thankyou.family.couple': 'Couple without children',
    'thankyou.family.baby': 'Couple with baby (up to 2 years)',
    'thankyou.family.children': 'Family with children (2-12 years)',
    'thankyou.family.teens': 'Family with teenagers',
    'thankyou.family.mixed': 'Mixed family (various ages)',
    'thankyou.diet.none': 'No restrictions',
    'thankyou.diet.vegetarian': 'Vegetarian',
    'thankyou.diet.lactose': 'Lactose-free',
    'thankyou.diet.gluten': 'Gluten-free',
    'thankyou.diet.diabetic': 'Diabetic',
    'thankyou.diet.multiple': 'Multiple restrictions',
    'thankyou.whatsapp.title': 'Wait for a WhatsApp message',
    'thankyou.whatsapp.message': 'We will send a message to {whatsapp} within 24 hours with your first weekly meal plan.',
    'thankyou.whatsapp.defaultNumber': 'your number',
    'thankyou.trial.title': 'Your free trial has started',
    'thankyou.trial.message': 'You have access to 7 days of personalized meal plans. Don\'t worry, we\'ll notify you before it ends.',
    'thankyou.button.home': 'Return to home page',
    
    // TermsOfUse page
    'terms.title': 'Terms of Use',
    'terms.lastUpdated': 'Last updated:',
    
    // PrivacyPolicy page
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated:',
    'privacy.section1.title': '1. Introduction',
    'privacy.section1.content1': 'Mamma\'s Plate Plan is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our meal planning service via WhatsApp.',
    'privacy.section1.content2': 'By using our service, you agree to the collection and use of information in accordance with this policy. This policy complies with the General Data Protection Law (LGPD) of Brazil.',
    'privacy.section2.title': '2. Information We Collect',
    'privacy.section2.content': 'To provide and improve our service, we collect various types of information, including:',
    'privacy.section2.1.title': '2.1 Personal Information',
    'privacy.section2.1.content': 'When you register and use Mamma\'s Plate Plan, we may collect the following personal information:',
    'privacy.section2.1.item1': 'Full name',
    'privacy.section2.1.item2': 'Phone number',
    'privacy.section2.1.item3': 'Email address',
    'privacy.section2.1.item4': 'Payment information (processed by third-party payment providers)',
    'privacy.section2.1.item5': 'Food preferences and dietary restrictions',
    'privacy.section2.1.item6': 'Family composition (number of people, ages)',
    'privacy.section2.2.title': '2.2 Usage Data',
    'privacy.section2.2.content': 'We also collect information about how you access and use our service, including:',
    'privacy.section2.2.item1': 'Interactions with our service via WhatsApp',
    'privacy.section2.2.item2': 'Menu preferences and recipe ratings',
    'privacy.section2.2.item3': 'Frequency of service use',
    'privacy.section2.2.item4': 'Usage patterns and behavior',
    'privacy.section3.title': '3. How We Use Your Information',
    'privacy.section3.content': 'We use the collected information to:',
    'privacy.section3.item1': 'Provide and maintain our meal planning service',
    'privacy.section3.item2': 'Personalize menus according to your preferences and needs',
    'privacy.section3.item3': 'Process payments and manage your subscription',
    'privacy.section3.item4': 'Send service-related notifications via WhatsApp',
    'privacy.section3.item5': 'Improve our service based on feedback and usage patterns',
    'privacy.section3.item6': 'Provide customer support',
    'privacy.section3.item7': 'Comply with legal obligations',
    'privacy.keywords': 'privacy policy, lgpd, data protection, mamma\'s plate plan, terms of use',
    'privacy.section4.title': '4. Information Sharing',
    'privacy.section4.content': 'We may share your personal information with:',
    'privacy.section4.item1': 'Third-party service providers that assist us in operating our service (such as payment processors and hosting services)',
    'privacy.section4.item2': 'Legal authorities when required by law or to protect our rights',
    'privacy.section4.item3': 'Business partners with your explicit consent',
    'privacy.section4.content2': 'We do not sell, rent, or trade your personal information to third parties.',
    'privacy.section5.title': '5. Data Security',
    'privacy.section5.content': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or accidental or unlawful destruction.',
    'privacy.section5.content2': 'However, no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.',
    'privacy.section6.title': '6. Cookies and Similar Technologies',
    'privacy.section6.content': 'Our website and services may use "cookies" and other tracking technologies to collect information about your activity, browser, and device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, some parts of our service may not function properly.',
    'privacy.section7.title': '7. Retention Period',
    'privacy.section7.content': 'We retain your personal information only for as long as necessary for the purposes set out in this Privacy Policy, unless a longer retention period is required or permitted by law.',
    'privacy.section7.content2': 'When we no longer have a legitimate need to process your personal information, we will delete or anonymize it. If this is not possible, we will securely store your personal information and isolate it from any further processing until deletion is possible.',
    'privacy.section8.title': '8. Your Rights',
    'privacy.section8.content': 'According to the LGPD and other applicable data protection laws, you have the following rights:',
    'privacy.section8.item1': 'Access: Right to access your personal information that we maintain.',
    'privacy.section8.item2': 'Correction: Right to correct inaccurate or incomplete information.',
    'privacy.section8.item3': 'Deletion: Right to request deletion of your personal information.',
    'privacy.section8.item4': 'Restriction: Right to request restriction of processing of your information.',
    'privacy.section8.item5': 'Portability: Right to receive your information in a structured and transferable format.',
    'privacy.section8.item6': 'Objection: Right to object to the processing of your information.',
    'privacy.section8.item7': 'Withdrawal of Consent: Right to withdraw your consent at any time.',
    'privacy.section8.content2': 'To exercise any of these rights, please contact us through the channels indicated in the "Contact" section below.',
    'privacy.section9.title': '9. International Data Transfers',
    'privacy.section9.content1': 'Your information may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ.',
    'privacy.section9.content2': 'When we transfer your data outside of Brazil, we ensure that appropriate protection measures are implemented, such as standard contractual clauses or recognized data protection certifications.',
    'privacy.section10.title': '10. Children',
    'privacy.section10.content': 'Our service is not intended for individuals under the age of 18. We do not knowingly collect personal information from children. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us so that we can take necessary actions.',
    'privacy.section11.title': '11. Changes to This Policy',
    'privacy.section11.content1': 'We may update our Privacy Policy periodically. We will notify you of any changes by posting the new Privacy Policy on this page and, if the changes are significant, we will send a notification via WhatsApp or email.',
    'privacy.section11.content2': 'We recommend that you review this Privacy Policy periodically for any changes.',
    'privacy.section12.title': '12. Contact',
    'privacy.section12.content': 'If you have any questions or concerns about this Privacy Policy or our data practices, please contact us:',
    'privacy.section12.email': 'Email:',
    'privacy.section12.emailAddress': 'privacy@mammasplateplan.com',
    'privacy.section12.address': 'Address:',
    'privacy.section12.addressValue': 'Av. Paulista, 171, São Paulo - SP, 01310-100, Brazil',
    'privacy.section12.dpo': 'Data Protection Officer (DPO):',
    'privacy.section12.dpoEmail': 'dpo@mammasplateplan.com',
    'terms.section1.title': '1. Acceptance of Terms',
    'terms.section1.content': 'By accessing and using the Mamma\'s Plate Plan service, you agree to comply with and be bound by the following terms and conditions. If you do not agree with any part of these terms, you may not access or use our services.',
    'terms.section2.title': '2. Service Description',
    'terms.section2.content': 'Mamma\'s Plate Plan is a personalized meal planning service delivered via WhatsApp. Our service offers weekly meal plans, recipes, shopping lists, and nutritional tips tailored to each family\'s needs and preferences.',
    'terms.section3.title': '3. Eligibility',
    'terms.section3.content': 'To use Mamma\'s Plate Plan, you must be at least 18 years old and have the legal capacity to enter into binding contracts. By using our service, you represent and warrant that you meet these requirements.',
    'terms.section4.title': '4. Registration and Account',
    'terms.section4.content': 'To access certain features of our service, you will need to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to:',
    'terms.section4.item1': 'Provide accurate, current, and complete information during the registration process;',
    'terms.section4.item2': 'Maintain and promptly update your registration information;',
    'terms.section4.item3': 'Notify us immediately of any unauthorized use of your account or any other security breach.',
    'terms.section5.title': '5. Plans and Payments',
    'terms.section5.content': 'Mamma\'s Plate Plan offers different subscription plans. By subscribing to a paid plan, you agree to pay all applicable fees as specified at the time of purchase. Payments are processed by third-party payment providers and are subject to the terms and conditions of those providers.',
    'terms.section5.content2': 'You may cancel your subscription at any time, but there will be no refunds for partial subscription periods. We reserve the right to change the prices of our services at any time, with appropriate prior notice.',
    'terms.section6.title': '6. Acceptable Use',
    'terms.section6.content': 'You agree to use Mamma\'s Plate Plan only for lawful purposes and in accordance with these Terms. You must not:',
    'terms.section6.item1': 'Use the service in any way that could damage, disable, or overburden the service;',
    'terms.section6.item2': 'Attempt to access areas of the service to which you do not have permission;',
    'terms.section6.item3': 'Use the service to distribute unsolicited advertising or promotional material;',
    'terms.section6.item4': 'Reproduce, duplicate, copy, sell, resell, or exploit any part of the service without express written permission.',
    'terms.section7.title': '7. Content and Intellectual Property',
    'terms.section7.content1': 'All content made available through Mamma\'s Plate Plan, including text, graphics, logos, icons, images, recipes, meal plans, and software, is the property of Mamma\'s Plate Plan or its content suppliers and is protected by copyright laws.',
    'terms.section7.content2': 'You may use the content only for your personal, non-commercial use. Any other use, including reproduction, modification, distribution, transmission, or republication, without the prior written consent of Mamma\'s Plate Plan, is strictly prohibited.',
    'terms.section8.title': '8. Disclaimer',
    'terms.section8.content': 'The nutritional information and recipes provided by Mamma\'s Plate Plan are for informational purposes only and do not substitute professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional before making significant changes to your diet, especially if you have pre-existing medical conditions.',
    'terms.section9.title': '9. Limitation of Liability',
    'terms.section9.content': 'Under no circumstances shall Mamma\'s Plate Plan, its directors, employees, partners, or agents be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use of or inability to use the service.',
    'terms.section10.title': '10. Service and Terms Modifications',
    'terms.section10.content': 'We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) at any time, with or without notice. We may also revise these Terms of Use at any time, at our discretion. By continuing to use the service after such changes, you agree to be bound by the revised terms.',
    'terms.section11.title': '11. Applicable Law',
    'terms.section11.content': 'These Terms shall be governed by and construed in accordance with the laws of Brazil, without regard to its conflict of law provisions.',
    'terms.section12.title': '12. Contact',
    'terms.section12.content': 'If you have any questions about these Terms, please contact us at: contact@mammasplateplan.com',
    'terms.keywords': 'terms of use, service conditions, contract, meal planning, legal terms'
  }
};
