// Define available languages
export type Language = 'pt-BR' | 'en-US';

// Translation dictionaries
export const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Navigation
    'nav.how_it_works': 'Como Funciona',
    'nav.pricing': 'Preços',
    'nav.faq': 'FAQ',
    'nav.free_trial': 'Teste Grátis',
    
    // Hero section
    'hero.title': 'Cardápios semanais personalizados para sua família',
    'hero.subtitle': 'Receba no WhatsApp cardápios personalizados, lista de compras e receitas. Economize tempo e dinheiro, sem estresse.',
    'hero.cta': 'Comece Grátis',
    'hero.secondary_cta': 'Saiba Mais',
    'hero.cta.trial': 'Comece seu teste de 7 dias grátis',
    'hero.cta.no_commitment': '✨ Sem compromisso • Cancele quando quiser',
    'hero.whatsapp.badge': 'Receba no WhatsApp',
    
    // Hero carousel slides
    'hero.slide1.title': 'Planejamento de',
    'hero.slide1.subtitle': 'Refeições para Mães',
    'hero.slide1.tagline': 'Introdução alimentar e receitas práticas',
    'hero.slide1.description': 'Receba cardápios especiais para bebês iniciando sólidos e receitas práticas para toda a família, sem complicação.',
    'hero.slide1.alt': 'Mãe preparando refeição saudável para bebê',
    'hero.slide1.feature1': 'Introdução alimentar',
    'hero.slide1.feature2': 'Para toda família',
    'hero.slide1.feature3': 'Receitas rápidas',
    'hero.slide1.feature4': 'Lista organizada',
    
    'hero.slide2.title': 'Planejamento de',
    'hero.slide2.subtitle': 'Refeições Especiais',
    'hero.slide2.tagline': 'Respeitando suas restrições alimentares',
    'hero.slide2.description': 'Cardápios personalizados para vegetarianos, intolerantes à lactose, celíacos e outras necessidades específicas.',
    'hero.slide2.alt': 'Pessoa preparando refeição com alimentos para dietas especiais',
    'hero.slide2.feature1': 'Sem restrições',
    'hero.slide2.feature2': 'Nutrição balanceada',
    'hero.slide2.feature3': 'Entrega semanal',
    'hero.slide2.feature4': 'Ingredientes certos',
    
    'hero.slide3.title': 'Planejamento de',
    'hero.slide3.subtitle': 'Refeições Práticas',
    'hero.slide3.tagline': 'Para profissionais ocupados',
    'hero.slide3.description': 'Cardápios otimizados para quem tem pouco tempo, mas não abre mão de uma alimentação saudável e saborosa.',
    'hero.slide3.alt': 'Profissional ocupado preparando refeição rápida e saudável',
    'hero.slide3.feature1': 'Vida corrida',
    'hero.slide3.feature2': 'Casais e solteiros',
    'hero.slide3.feature3': 'Preparo rápido',
    'hero.slide3.feature4': 'Compra eficiente',
    
    // Features section
    'features.title': 'Cardápios que se adaptam à sua família',
    'features.subtitle': 'Soluções práticas para o dia a dia',
    'features.personalized.title': 'Personalizado',
    'features.personalized.description': 'Cardápios adaptados às preferências e restrições alimentares da sua família.',
    'features.practical.title': 'Prático',
    'features.practical.description': 'Receba tudo pelo WhatsApp, sem precisar baixar aplicativos ou fazer login.',
    'features.economical.title': 'Econômico',
    'features.economical.description': 'Economize tempo e dinheiro com listas de compras otimizadas e receitas aproveitáveis.',
    'features.nutritious.title': 'Nutritivo',
    'features.nutritious.description': 'Cardápios elaborados por nutricionistas, garantindo refeições balanceadas.',
    'features.adaptable.title': 'Adaptável',
    'features.adaptable.description': 'Receitas que se adaptam à rotina da sua família, com opções rápidas para dias corridos.',
    'features.supportive.title': 'Suporte',
    'features.supportive.description': 'Atendimento personalizado para ajustar seu cardápio quando necessário.',
    
    // Features component
    'features.component.heading': 'Tudo que você precisa',
    'features.component.subheading': 'Simplificamos o planejamento das refeições para mães ocupadas, pessoas com restrições alimentares e profissionais com rotina corrida.',
    'features.component.card1.title': 'Cardápio Personalizado',
    'features.component.card1.description': 'Refeições planejadas com base no perfil da sua família, idade das crianças e preferências alimentares.',
    'features.component.card2.title': 'Lista de Compras Organizada',
    'features.component.card2.description': 'Ingredientes organizados por categoria com checkboxes para uma compra mais eficiente.',
    'features.component.card3.title': 'Culinária Brasileira',
    'features.component.card3.description': 'Pratos que fazem parte da nossa cultura, com ingredientes sazonais e de fácil acesso.',
    'features.component.card4.title': 'Nutrição Balanceada',
    'features.component.card4.description': 'Refeições equilibradas para famílias, pessoas com restrições alimentares e profissionais ocupados.',
    'features.component.card5.title': 'Praticidade Total',
    'features.component.card5.description': 'Sem aplicativo, sem login, sem complicação. Tudo direto no seu WhatsApp.',
    'features.component.card6.title': 'Para Todos os Perfis',
    'features.component.card6.description': 'Famílias com bebês, pessoas com restrições alimentares e profissionais com pouco tempo para cozinhar.',
    
    // Blog section
    'blog.title': 'Blog e Receitas',
    'blog.subtitle': 'Dicas, cardápios e receitas para inspirar sua rotina alimentar',
    'blog.servings': 'porções',
    'blog.readMore': 'Ler mais',
    'blog.viewMore': 'Ver mais artigos',
    
    // How it works section
    'how.title': 'Como Funciona',
    'how.subtitle': 'Três passos simples para transformar sua rotina alimentar',
    'how.step1.title': 'Cadastre-se',
    'how.step1.description': 'Preencha um breve questionário sobre sua família, preferências e restrições alimentares.',
    'how.step2.title': 'Receba seu cardápio',
    'how.step2.description': 'Toda semana você receberá no WhatsApp um cardápio personalizado com lista de compras.',
    'how.step3.title': 'Prepare as refeições',
    'how.step3.description': 'Siga as receitas simples e práticas para preparar refeições deliciosas para sua família.',
    
    // HowItWorks component
    'how.component.heading': 'Como funciona?',
    'how.component.subheading': 'Em apenas 3 passos simples, você terá um planejamento completo de refeições para toda a semana.',
    'how.component.step1.title': 'Crie seu perfil',
    'how.component.step1.description': 'Conte sobre sua família, idades das crianças, restrições alimentares e preferências.',
    'how.component.step2.title': 'Receba no WhatsApp',
    'how.component.step2.description': 'Toda segunda-feira receba seu cardápio da semana e lista de compras organizada.',
    'how.component.step3.title': 'Cozinhe e aproveite',
    'how.component.step3.description': 'Siga o planejamento e tenha mais tempo para curtir momentos em família.',
    
    // Pricing section
    'pricing.title': 'Planos e Preços',
    'pricing.subtitle': 'Escolha o plano ideal para sua família',
    'pricing.monthly.title': 'Mensal',
    'pricing.monthly.price': 'R$29,90',
    'pricing.monthly.period': '/mês',
    'pricing.monthly.description': 'Ideal para experimentar o serviço',
    'pricing.quarterly.title': 'Trimestral',
    'pricing.quarterly.price': 'R$79,90',
    'pricing.quarterly.period': '/trimestre',
    'pricing.quarterly.description': 'Economize R$9,80 por trimestre',
    'pricing.annual.title': 'Anual',
    'pricing.annual.price': 'R$299,90',
    'pricing.annual.period': '/ano',
    'pricing.annual.description': 'Economize R$58,90 por ano',
    'pricing.feature.cardapios': 'Cardápios semanais personalizados',
    'pricing.feature.lista': 'Lista de compras organizada',
    'pricing.feature.receitas': 'Receitas detalhadas',
    'pricing.feature.ajustes': 'Ajustes sob demanda',
    'pricing.feature.suporte': 'Suporte via WhatsApp',
    'pricing.cta': 'Começar Agora',
    'pricing.trial': 'Teste grátis de 7 dias',
    
    // Pricing component
    'pricing.component.heading': 'Planos que cabem no seu orçamento',
    'pricing.component.subheading': 'Comece gratuitamente e descubra como é fácil planejar as refeições da família.',
    'pricing.component.badge': 'Teste Grátis',
    'pricing.component.plan.title': 'Plano Mensal',
    'pricing.component.plan.price': 'R$ 14,90',
    'pricing.component.plan.period': '/mês',
    'pricing.component.plan.trial': '7 dias grátis para testar',
    'pricing.component.features.1': 'Cardápio semanal personalizado',
    'pricing.component.features.2': 'Lista de compras organizada',
    'pricing.component.features.3': 'Refeições para almoço e jantar',
    'pricing.component.features.4': 'Ingredientes sazonais e locais',
    'pricing.component.features.5': 'Suporte via WhatsApp',
    'pricing.component.features.6': 'Receitas da culinária brasileira',
    'pricing.component.features.7': 'Cancelamento a qualquer momento',
    'pricing.component.cta': 'Comece seu teste grátis agora',
    'pricing.component.disclaimer': 'Sem compromisso • Sem fidelidade • Cancele quando quiser',
    'pricing.component.customization': '💡 <strong>Personalizações extras:</strong> Planos especiais disponíveis para famílias com necessidades específicas (vegano, sem glúten, diabético, etc.)',
    
    // Testimonials component
    'testimonials.component.heading': 'O que nossos usuários estão falando',
    'testimonials.component.subheading': 'Famílias, pessoas com restrições alimentares e profissionais ocupados já transformaram sua rotina.',
    'testimonials.component.rating.text': 'Baseado em 127 avaliações',
    'testimonials.component.testimonial1.name': 'Maria Silva',
    'testimonials.component.testimonial1.role': 'Mãe de 2 filhos',
    'testimonials.component.testimonial1.content': 'Minha vida mudou! Não preciso mais ficar estressada pensando no que fazer para o almoço. As receitas são deliciosas e os ingredientes sempre frescos.',
    'testimonials.component.testimonial1.avatar': '👩‍🍳',
    'testimonials.component.testimonial2.name': 'Ana Costa',
    'testimonials.component.testimonial2.role': 'Mãe de bebê de 8 meses',
    'testimonials.component.testimonial2.content': 'Perfeito para quem está introduzindo alimentação sólida. As sugestões são nutritivas e adequadas para a idade do meu filho.',
    'testimonials.component.testimonial2.avatar': '👶',
    'testimonials.component.testimonial3.name': 'Carlos Mendes',
    'testimonials.component.testimonial3.role': 'Executivo, intolerante à lactose',
    'testimonials.component.testimonial3.content': 'Finalmente encontrei um serviço que entende minhas restrições alimentares. Recebo receitas deliciosas sem lactose toda semana.',
    'testimonials.component.testimonial3.avatar': '👨‍💼',
    'testimonials.component.testimonial4.name': 'Rafael & Juliana',
    'testimonials.component.testimonial4.role': 'Casal profissional',
    'testimonials.component.testimonial4.content': 'Economizamos tempo e dinheiro. A lista de compras é super organizada e não desperdiçamos mais comida. Perfeito para nossa rotina corrida!',
    'testimonials.component.testimonial4.avatar': '👫',
    
    // FAQ section
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Tire suas dúvidas sobre o Cardápio Fácil e como podemos ajudar sua família',
    'faq.item1.question': 'Como funciona o Cardápio Fácil?',
    'faq.item1.answer': 'Após se cadastrar, você receberá semanalmente no seu WhatsApp um cardápio personalizado com base no perfil da sua família, incluindo lista de compras organizada e receitas detalhadas. Tudo isso sem precisar baixar aplicativos ou fazer login em plataformas complicadas.',
    'faq.item2.question': 'Quanto custa o serviço?',
    'faq.item2.answer': 'Oferecemos um teste gratuito de 7 dias para que você experimente o serviço sem compromisso. Após esse período, o valor é de R$29,90 por mês, com possibilidade de cancelamento a qualquer momento.',
    'faq.item3.question': 'Como são elaborados os cardápios?',
    'faq.item3.answer': 'Nossos cardápios são elaborados por nutricionistas especializados, considerando as necessidades nutricionais da sua família, preferências alimentares e eventuais restrições. Utilizamos ingredientes sazonais e de fácil acesso em supermercados.',
    'faq.item4.question': 'Posso personalizar meu cardápio?',
    'faq.item4.answer': 'Sim! Durante o cadastro, você informa o perfil da sua família, incluindo número de pessoas, idades, preferências e restrições alimentares. Além disso, você pode solicitar ajustes a qualquer momento respondendo às mensagens no WhatsApp.',
    'faq.item5.question': 'Como funciona para famílias com bebês?',
    'faq.item5.answer': 'Para famílias com bebês, incluímos orientações específicas para introdução alimentar, respeitando a idade da criança e as recomendações pediátricas atuais, com receitas adaptadas que toda a família pode consumir.',
    'faq.item6.question': 'E se eu tiver restrições alimentares?',
    'faq.item6.answer': 'Nossos cardápios são totalmente adaptáveis para diversas restrições alimentares, como intolerância à lactose, glúten, vegetarianismo, veganismo e alergias específicas. Basta informar suas necessidades no cadastro.',
    'faq.item7.question': 'Posso cancelar a qualquer momento?',
    'faq.item7.answer': 'Sim, você pode cancelar sua assinatura a qualquer momento, sem multas ou taxas adicionais. Basta enviar uma mensagem pelo WhatsApp solicitando o cancelamento.',
    'faq.item8.question': 'Como é feito o pagamento?',
    'faq.item8.answer': 'O pagamento é feito mensalmente via PIX ou cartão de crédito. Você receberá as instruções de pagamento após o período de teste gratuito.',
    
    // CTA section
    'cta.title': 'Pronto para simplificar sua rotina alimentar?',
    'cta.subtitle': 'Comece seu teste grátis de 7 dias agora e receba cardápios personalizados para sua família',
    'cta.form.name.label': 'Nome completo',
    'cta.form.name.placeholder': 'Digite seu nome completo',
    'cta.form.name.error': 'Nome deve ter pelo menos 3 caracteres',
    'cta.form.whatsapp.label': 'WhatsApp',
    'cta.form.whatsapp.placeholder': '(00) 00000-0000',
    'cta.form.whatsapp.error': 'WhatsApp inválido',
    'cta.form.familySize.label': 'Tamanho da família',
    'cta.form.familySize.placeholder': 'Quantas pessoas?',
    'cta.form.familySize.error': 'Selecione o tamanho da família',
    'cta.form.familySize.option.1': '1 pessoa',
    'cta.form.familySize.option.2': '2 pessoas',
    'cta.form.familySize.option.3': '3 pessoas',
    'cta.form.familySize.option.4': '4 pessoas',
    'cta.form.familySize.option.5': '5 ou mais pessoas',
    'cta.form.dietaryRestrictions.label': 'Restrições alimentares',
    'cta.form.dietaryRestrictions.placeholder': 'Alguma restrição ou preferência?',
    'cta.form.dietaryRestrictions.option.none': 'Nenhuma restrição',
    'cta.form.dietaryRestrictions.option.vegetarian': 'Vegetariano',
    'cta.form.dietaryRestrictions.option.lactose': 'Sem lactose',
    'cta.form.dietaryRestrictions.option.gluten': 'Sem glúten',
    'cta.form.dietaryRestrictions.option.diabetic': 'Diabético',
    'cta.form.dietaryRestrictions.option.multiple': 'Múltiplas restrições',
    'cta.form.button.loading': 'Processando...',
    'cta.form.button.submit': 'Começar teste grátis de 7 dias',
    'cta.form.terms.text': 'Aceito os',
    'cta.form.terms.link': 'termos de uso',
    'cta.form.terms.error': 'Você precisa aceitar os termos de uso',
    'cta.form.privacy.text': 'Aceito a',
    'cta.form.privacy.link': 'política de privacidade',
    'cta.form.privacy.error': 'Você precisa aceitar a política de privacidade',
    'cta.form.confirmation': 'Seu primeiro cardápio chegará em até 24 horas após a confirmação do cadastro.',
    'cta.form.error.title': 'Por favor, corrija os erros no formulário',
    'cta.form.error.description': 'Alguns campos precisam ser preenchidos corretamente.',
    'cta.form.success.title': 'Cadastro realizado com sucesso!',
    'cta.form.success.description': 'Enviamos uma mensagem de boas-vindas para o seu WhatsApp. Verifique seu celular.',
    'cta.button': 'Começar Teste Grátis',
    'cta.freeTrial': '7 dias grátis • Sem compromisso',
    'cta.form.title': 'Cadastre-se gratuitamente',
    'cta.form.description': 'Leva menos de 2 minutos para começar',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados',
    'footer.terms': 'Termos de Uso',
    'footer.privacy': 'Política de Privacidade',
    'footer.contact': 'Contato',
    
    // Theme toggle
    'theme.toggle': 'Alternar tema',
    
    // Language toggle
    'language.toggle': 'Mudar idioma',
    'language.pt': 'Português',
    'language.en': 'English'
  },
  'en-US': {
    // Navigation
    'nav.how_it_works': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.free_trial': 'Free Trial',
    
    // Hero section
    'hero.title': 'Personalized weekly meal plans for your family',
    'hero.subtitle': 'Receive personalized meal plans, shopping lists, and recipes via WhatsApp. Save time and money, without stress.',
    'hero.cta': 'Start Free',
    'hero.secondary_cta': 'Learn More',
    'hero.cta.trial': 'Start your 14-day free trial',
    'hero.cta.no_commitment': '✨ No commitment • Cancel anytime',
    'hero.whatsapp.badge': 'Receive on WhatsApp',
    
    // Hero carousel slides
    'hero.slide1.title': 'Meal Planning',
    'hero.slide1.subtitle': 'For Mothers',
    'hero.slide1.tagline': 'Baby food introduction and practical recipes',
    'hero.slide1.description': 'Receive special meal plans for babies starting solids and practical recipes for the whole family, without complications.',
    'hero.slide1.alt': 'Mother preparing healthy meal for baby',
    'hero.slide1.feature1': 'Baby food introduction',
    'hero.slide1.feature2': 'For the whole family',
    'hero.slide1.feature3': 'Quick recipes',
    'hero.slide1.feature4': 'Organized shopping list',
    
    'hero.slide2.title': 'Meal Planning',
    'hero.slide2.subtitle': 'For Special Diets',
    'hero.slide2.tagline': 'Respecting your dietary restrictions',
    'hero.slide2.description': 'Customized meal plans for vegetarians, lactose intolerant, celiacs, and other specific dietary needs.',
    'hero.slide2.alt': 'Person preparing meal with special diet foods',
    'hero.slide2.feature1': 'No restrictions',
    'hero.slide2.feature2': 'Balanced nutrition',
    'hero.slide2.feature3': 'Weekly delivery',
    'hero.slide2.feature4': 'Right ingredients',
    
    'hero.slide3.title': 'Meal Planning',
    'hero.slide3.subtitle': 'For Busy Professionals',
    'hero.slide3.tagline': 'For busy professionals',
    'hero.slide3.description': 'Optimized meal plans for those with little time, but who don\'t compromise on healthy and tasty food.',
    'hero.slide3.alt': 'Busy professional preparing quick and healthy meal',
    'hero.slide3.feature1': 'Busy lifestyle',
    'hero.slide3.feature2': 'Singles and couples',
    'hero.slide3.feature3': 'Quick preparation',
    'hero.slide3.feature4': 'Efficient shopping',
    
    // Features section
    'features.title': 'Meal plans that adapt to your family',
    'features.subtitle': 'Practical solutions for everyday life',
    'features.personalized.title': 'Personalized',
    'features.personalized.description': 'Meal plans adapted to your family\'s preferences and dietary restrictions.',
    'features.practical.title': 'Practical',
    'features.practical.description': 'Receive everything via WhatsApp, no need to download apps or log in.',
    'features.economical.title': 'Economical',
    'features.economical.description': 'Save time and money with optimized shopping lists and reusable recipes.',
    'features.nutritious.title': 'Nutritious',
    'features.nutritious.description': 'Meal plans created by nutritionists, ensuring balanced meals.',
    'features.adaptable.title': 'Adaptable',
    'features.adaptable.description': 'Recipes that adapt to your family\'s routine, with quick options for busy days.',
    'features.supportive.title': 'Support',
    'features.supportive.description': 'Personalized assistance to adjust your meal plan when needed.',
    
    // Features component
    'features.component.heading': 'Everything you need',
    'features.component.subheading': 'We simplify meal planning for busy mothers, people with dietary restrictions, and professionals with hectic routines.',
    'features.component.card1.title': 'Personalized Meal Plan',
    'features.component.card1.description': 'Meals planned based on your family profile, children\'s ages, and food preferences.',
    'features.component.card2.title': 'Organized Shopping List',
    'features.component.card2.description': 'Ingredients organized by category with checkboxes for more efficient shopping.',
    'features.component.card3.title': 'Brazilian Cuisine',
    'features.component.card3.description': 'Dishes that are part of our culture, with seasonal and easily accessible ingredients.',
    'features.component.card4.title': 'Balanced Nutrition',
    'features.component.card4.description': 'Balanced meals for families, people with dietary restrictions, and busy professionals.',
    'features.component.card5.title': 'Total Convenience',
    'features.component.card5.description': 'No app, no login, no complications. Everything directly on your WhatsApp.',
    'features.component.card6.title': 'For All Profiles',
    'features.component.card6.description': 'Families with babies, people with dietary restrictions, and professionals with little time to cook.',
    
    // Blog section
    'blog.title': 'Blog & Recipes',
    'blog.subtitle': 'Tips, meal plans and recipes to inspire your meal routine',
    'blog.servings': 'servings',
    'blog.readMore': 'Read more',
    'blog.viewMore': 'View more articles',
    
    // How it works section
    'how.title': 'How It Works',
    'how.subtitle': 'Three simple steps to transform your meal routine',
    'how.step1.title': 'Sign Up',
    'how.step1.description': 'Fill out a brief questionnaire about your family, preferences, and dietary restrictions.',
    'how.step2.title': 'Receive your meal plan',
    'how.step2.description': 'Every week you\'ll receive a personalized meal plan with a shopping list via WhatsApp.',
    'how.step3.title': 'Prepare the meals',
    'how.step3.description': 'Follow the simple and practical recipes to prepare delicious meals for your family.',
    
    // HowItWorks component
    'how.component.heading': 'How does it work?',
    'how.component.subheading': 'In just 3 simple steps, you\'ll have a complete meal plan for the entire week.',
    'how.component.step1.title': 'Create your profile',
    'how.component.step1.description': 'Tell us about your family, children\'s ages, dietary restrictions, and preferences.',
    'how.component.step2.title': 'Receive on WhatsApp',
    'how.component.step2.description': 'Every Monday receive your weekly meal plan and organized shopping list.',
    'how.component.step3.title': 'Cook and enjoy',
    'how.component.step3.description': 'Follow the plan and have more time to enjoy moments with your family.',
    
    // Pricing section
    'pricing.title': 'Plans and Pricing',
    'pricing.subtitle': 'Choose the ideal plan for your family',
    'pricing.monthly.title': 'Monthly',
    'pricing.monthly.price': '$5.99',
    'pricing.monthly.period': '/month',
    'pricing.monthly.description': 'Ideal for trying out the service',
    'pricing.quarterly.title': 'Quarterly',
    'pricing.quarterly.price': '$14.99',
    'pricing.quarterly.period': '/quarter',
    'pricing.quarterly.description': 'Save $3 per quarter',
    'pricing.annual.title': 'Annual',
    'pricing.annual.price': '$59.99',
    'pricing.annual.period': '/year',
    'pricing.annual.description': 'Save $12 per year',
    'pricing.feature.cardapios': 'Personalized weekly meal plans',
    'pricing.feature.lista': 'Organized shopping list',
    'pricing.feature.receitas': 'Detailed recipes',
    'pricing.feature.ajustes': 'On-demand adjustments',
    'pricing.feature.suporte': 'WhatsApp support',
    'pricing.cta': 'Start Now',
    'pricing.trial': '7-day free trial',
    
    // Pricing component
    'pricing.component.heading': 'Plans that fit your budget',
    'pricing.component.subheading': 'Start for free and discover how easy it is to plan family meals.',
    'pricing.component.badge': 'Free Trial',
    'pricing.component.plan.title': 'Monthly Plan',
    'pricing.component.plan.price': '$ 4.99',
    'pricing.component.plan.period': '/month',
    'pricing.component.plan.trial': '7 days free to try',
    'pricing.component.features.1': 'Personalized weekly meal plan',
    'pricing.component.features.2': 'Organized shopping list',
    'pricing.component.features.3': 'Meals for lunch and dinner',
    'pricing.component.features.4': 'Seasonal and local ingredients',
    'pricing.component.features.5': 'WhatsApp support',
    'pricing.component.features.6': 'Brazilian cuisine recipes',
    'pricing.component.features.7': 'Cancel anytime',
    'pricing.component.cta': 'Start your free trial now',
    'pricing.component.disclaimer': 'No commitment • No loyalty period • Cancel whenever you want',
    'pricing.component.customization': '💡 <strong>Extra customizations:</strong> Special plans available for families with specific needs (vegan, gluten-free, diabetic, etc.)',
    
    // Testimonials component
    'testimonials.component.heading': 'What our users are saying',
    'testimonials.component.subheading': 'Families, people with dietary restrictions, and busy professionals have already transformed their routine.',
    'testimonials.component.rating.text': 'Based on 127 reviews',
    'testimonials.component.testimonial1.name': 'Mary Smith',
    'testimonials.component.testimonial1.role': 'Mother of 2 children',
    'testimonials.component.testimonial1.content': 'My life has changed! I no longer need to stress about what to make for lunch. The recipes are delicious and the ingredients always fresh.',
    'testimonials.component.testimonial1.avatar': '👩‍🍳',
    'testimonials.component.testimonial2.name': 'Anna Costa',
    'testimonials.component.testimonial2.role': 'Mother of an 8-month-old baby',
    'testimonials.component.testimonial2.content': 'Perfect for those introducing solid foods. The suggestions are nutritious and appropriate for my son\'s age.',
    'testimonials.component.testimonial2.avatar': '👶',
    'testimonials.component.testimonial3.name': 'Charles Miller',
    'testimonials.component.testimonial3.role': 'Executive, lactose intolerant',
    'testimonials.component.testimonial3.content': 'I finally found a service that understands my dietary restrictions. I receive delicious lactose-free recipes every week.',
    'testimonials.component.testimonial3.avatar': '👨‍💼',
    'testimonials.component.testimonial4.name': 'Robert & Julia',
    'testimonials.component.testimonial4.role': 'Professional couple',
    'testimonials.component.testimonial4.content': 'We save time and money. The shopping list is super organized and we no longer waste food. Perfect for our busy routine!',
    'testimonials.component.testimonial4.avatar': '👫',
    
    // FAQ section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Get answers to common questions about Mamma\'s Plate Plan and how we can help your family',
    'faq.item1.question': 'How does Mamma\'s Plate Plan work?',
    'faq.item1.answer': 'After signing up, you\'ll receive a personalized weekly menu on your WhatsApp based on your family\'s profile, including an organized shopping list and detailed recipes. All this without having to download apps or log into complicated platforms.',
    'faq.item2.question': 'How much does the service cost?',
    'faq.item2.answer': 'We offer a 7-day free trial so you can experience the service without commitment. After this period, the cost is $29.90 per month, with the possibility of cancellation at any time.',
    'faq.item3.question': 'How are the menus created?',
    'faq.item3.answer': 'Our menus are created by specialized nutritionists, considering your family\'s nutritional needs, food preferences, and any restrictions. We use seasonal ingredients that are easily accessible in supermarkets.',
    'faq.item4.question': 'Can I customize my menu?',
    'faq.item4.answer': 'Yes! During registration, you provide your family\'s profile, including the number of people, ages, preferences, and dietary restrictions. Additionally, you can request adjustments at any time by responding to messages on WhatsApp.',
    'faq.item5.question': 'How does it work for families with babies?',
    'faq.item5.answer': 'For families with babies, we include specific guidelines for introducing solid foods, respecting the child\'s age and current pediatric recommendations, with adapted recipes that the whole family can consume.',
    'faq.item6.question': 'What if I have dietary restrictions?',
    'faq.item6.answer': 'Our menus are fully adaptable for various dietary restrictions, such as lactose intolerance, gluten, vegetarianism, veganism, and specific allergies. Just inform us of your needs during registration.',
    'faq.item7.question': 'Can I cancel at any time?',
    'faq.item7.answer': 'Yes, you can cancel your subscription at any time, without penalties or additional fees. Simply send a message via WhatsApp requesting cancellation.',
    'faq.item8.question': 'How is payment made?',
    'faq.item8.answer': 'Payment is made monthly via PIX or credit card. You will receive payment instructions after the free trial period.',
    
    // CTA section
    'cta.title': 'Ready to simplify your meal routine?',
    'cta.subtitle': 'Start your 7-day free trial now and receive personalized menus for your family',
    'cta.form.name.label': 'Full name',
    'cta.form.name.placeholder': 'Enter your full name',
    'cta.form.name.error': 'Name must have at least 3 characters',
    'cta.form.whatsapp.label': 'WhatsApp',
    'cta.form.whatsapp.placeholder': '(00) 00000-0000',
    'cta.form.whatsapp.error': 'Invalid WhatsApp number',
    'cta.form.familySize.label': 'Family size',
    'cta.form.familySize.placeholder': 'How many people?',
    'cta.form.familySize.error': 'Please select family size',
    'cta.form.familySize.option.1': '1 person',
    'cta.form.familySize.option.2': '2 people',
    'cta.form.familySize.option.3': '3 people',
    'cta.form.familySize.option.4': '4 people',
    'cta.form.familySize.option.5': '5 or more people',
    'cta.form.dietaryRestrictions.label': 'Dietary restrictions',
    'cta.form.dietaryRestrictions.placeholder': 'Any restrictions or preferences?',
    'cta.form.dietaryRestrictions.option.none': 'No restrictions',
    'cta.form.dietaryRestrictions.option.vegetarian': 'Vegetarian',
    'cta.form.dietaryRestrictions.option.lactose': 'Lactose-free',
    'cta.form.dietaryRestrictions.option.gluten': 'Gluten-free',
    'cta.form.dietaryRestrictions.option.diabetic': 'Diabetic',
    'cta.form.dietaryRestrictions.option.multiple': 'Multiple restrictions',
    'cta.form.button.loading': 'Processing...',
    'cta.form.button.submit': 'Start 7-day free trial',
    'cta.form.terms.text': 'I accept the',
    'cta.form.terms.link': 'terms of use',
    'cta.form.terms.error': 'You must accept the terms of use',
    'cta.form.privacy.text': 'I accept the',
    'cta.form.privacy.link': 'privacy policy',
    'cta.form.privacy.error': 'You must accept the privacy policy',
    'cta.form.confirmation': 'Your first menu will arrive within 24 hours after registration confirmation.',
    'cta.form.error.title': 'Please correct the errors in the form',
    'cta.form.error.description': 'Some fields need to be filled out correctly.',
    'cta.form.success.title': 'Registration successful!',
    'cta.form.success.description': 'We sent a welcome message to your WhatsApp. Check your phone.',
    'cta.button': 'Start Free Trial',
    'cta.freeTrial': '7 days free • No commitment',
    'cta.form.title': 'Sign up for free',
    'cta.form.description': 'Takes less than 2 minutes to start',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.terms': 'Terms of Use',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact',
    
    // Theme toggle
    'theme.toggle': 'Toggle theme',
    
    // Language toggle
    'language.toggle': 'Change language',
    'language.pt': 'Português',
    'language.en': 'English'
  }
};
